// seo-04 render boundary — the build-safe TanStack route template + image
// helpers. The LLM never emits JSX; this deterministic template renders it, so a
// bad generation can't break the build. Image placement per
// docs/research/image-placement-layout.md.

// Only the render fields reach the route file (never the generation prompt/seed).
export const pickImg = (im) =>
  im ? { src: im.src, alt: im.alt, caption: im.caption || '', width: im.width, height: im.height } : null;

const esc = (s) => String(s).replace(/"/g, '&quot;');

const imgTag = (im) => {
  const cap = im.caption || '';
  return (
    `<figure class="my-10">` +
    `<img src="${im.src}" alt="${esc(im.alt || cap)}" width="${im.width}" height="${im.height}" ` +
    `loading="lazy" decoding="async" style="aspect-ratio:3/2;object-fit:cover;width:100%" />` +
    (cap ? `<figcaption>${esc(cap)}</figcaption>` : '') +
    `</figure>`
  );
};

// Inline images go AFTER the first <p> of a section (never orphaned under a
// heading), skipping the first section since the hero already leads the page.
function injectImages(bodyHtml, inlineImgs) {
  if (!inlineImgs.length) return bodyHtml;
  let seen = 0;
  let placed = 0;
  return bodyHtml.replace(/<h2[\s\S]*?<\/p>/g, (m) => {
    seen++;
    return seen > 1 && placed < inlineImgs.length ? `${m}\n${imgTag(inlineImgs[placed++])}` : m;
  });
}

export function renderRoute({ slug, routePath, canonical, skillId, model, content, hero, inlineImgs, bodyHtml, jsonLd,
  ctaLabel = 'Get started', ctaUrl = '/', eyebrow = 'Guide' }) {
  const J = (v) => JSON.stringify(v);
  const BODY = injectImages(bodyHtml, inlineImgs);
  return `import { useRef } from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { AnalyticsEvent, track } from '../../lib/analytics'
import { useHexCopy, withColorChips } from '../../lib/color-chips'

// Generated by .skills/${skillId} from the seo-02 brief "${slug}".
// Content drafted by ${model} from a live-SERP brief. EDIT FREELY before launch.
// Inline-cited sources are unverified research leads; confirm any factual claim.

const META_TITLE = ${J(content.meta_title)}
const META_DESCRIPTION = ${J(content.meta_description)}
const CANONICAL = ${J(canonical)}
const H1 = ${J(content.h1)}
const LEDE = ${J(content.lede)}
const HERO = ${J(hero)}
const BODY_HTML = ${J(BODY)}
const FAQ: { q: string; a: string }[] = ${J(content.faq || [])}
const SOURCES: { label: string; url: string }[] = ${J(content.sources || [])}
const CLOSING_HEADING = ${J(content.closing_cta_heading || 'Skip the blank canvas')}
const CLOSING_TEXT = ${J(content.closing_cta_text || '')}
const JSON_LD = ${J(jsonLd)}

// Inline hex colors in the body render as click-to-copy swatch chips (see
// src/lib/color-chips). The hex stays as selectable text; only text is touched.
const BODY_WITH_CHIPS = withColorChips(BODY_HTML)

export const Route = createFileRoute('${routePath}')({
  head: () => ({
    meta: [
      { title: META_TITLE },
      { name: 'description', content: META_DESCRIPTION },
      { property: 'og:title', content: META_TITLE },
      { property: 'og:description', content: META_DESCRIPTION },
      { property: 'og:type', content: 'article' },
      { property: 'og:url', content: CANONICAL },
    ],
    links: [
      { rel: 'canonical', href: CANONICAL },
      ...(HERO ? [{ rel: 'preload', as: 'image', href: HERO.src }] : []),
    ],
  }),
  component: GuidePage,
})

function GuidePage() {
  const navigate = useNavigate()
  const articleRef = useRef<HTMLElement>(null)
  useHexCopy(articleRef)
  const startQuiz = () => {
    track(AnalyticsEvent.CREATE_BOARD_CLICKED, { source: 'guide:${slug}' })
    navigate({ to: '${ctaUrl}' })
  }
  return (
    <main className="mx-auto w-full max-w-3xl px-4 py-12 sm:px-6">
      <p className="mb-2 text-xs font-medium uppercase tracking-[0.18em] text-rose-900/70 dark:text-rose-300/70">
        ${eyebrow}
      </p>
      <h1 className="mb-4 font-serif text-4xl font-semibold leading-tight text-stone-900 sm:text-5xl dark:text-stone-100">
        {H1}
      </h1>
      <p className="mb-6 max-w-2xl text-lg leading-8 text-stone-600 dark:text-stone-300">{LEDE}</p>
      {HERO && (
        <figure className="mb-10">
          <img
            src={HERO.src}
            alt={HERO.alt}
            width={HERO.width}
            height={HERO.height}
            className="w-full rounded-2xl object-cover"
            style={{ aspectRatio: '3 / 2' }}
            loading="eager"
            fetchPriority="high"
            decoding="async"
          />
          {HERO.caption && (
            <figcaption className="mt-2 text-sm text-stone-500 dark:text-stone-400">{HERO.caption}</figcaption>
          )}
        </figure>
      )}
      <button
        onClick={startQuiz}
        className="mb-10 inline-flex rounded-full bg-rose-900 px-5 py-2.5 text-sm font-medium text-stone-50 shadow-sm transition-all hover:-translate-y-0.5 hover:bg-rose-950 dark:bg-rose-300 dark:text-rose-950 dark:hover:bg-rose-200"
      >
        ${ctaLabel}
      </button>
      <article
        ref={articleRef}
        className="prose prose-stone max-w-none dark:prose-invert prose-headings:font-serif prose-a:text-rose-900 prose-img:rounded-xl dark:prose-a:text-rose-300"
        dangerouslySetInnerHTML={{ __html: BODY_WITH_CHIPS }}
      />
      {FAQ.length > 0 && (
        <section className="mt-14">
          <h2 className="mb-4 font-serif text-2xl font-semibold text-stone-900 dark:text-stone-100">
            Frequently asked questions
          </h2>
          <dl className="space-y-5">
            {FAQ.map((f) => (
              <div key={f.q}>
                <dt className="font-medium text-stone-900 dark:text-stone-100">{f.q}</dt>
                <dd className="mt-1 text-stone-600 dark:text-stone-300">{f.a}</dd>
              </div>
            ))}
          </dl>
        </section>
      )}
      <section className="mt-14 rounded-2xl bg-rose-50 p-6 text-center sm:p-8 dark:bg-rose-950/30">
        <h2 className="mb-2 font-serif text-2xl font-semibold text-stone-900 dark:text-stone-100">
          {CLOSING_HEADING}
        </h2>
        {CLOSING_TEXT && (
          <p className="mx-auto mb-5 max-w-xl text-stone-600 dark:text-stone-300">{CLOSING_TEXT}</p>
        )}
        <button
          onClick={startQuiz}
          className="inline-flex rounded-full bg-rose-900 px-6 py-3 font-medium text-stone-50 shadow-sm transition-all hover:-translate-y-0.5 hover:bg-rose-950 dark:bg-rose-300 dark:text-rose-950 dark:hover:bg-rose-200"
        >
          ${ctaLabel}
        </button>
      </section>
      {SOURCES.length > 0 && (
        <section className="mt-12 border-t border-stone-200 pt-6 dark:border-stone-800">
          <p className="mb-2 text-xs font-medium uppercase tracking-[0.14em] text-stone-500">Sources</p>
          <ul className="space-y-1 text-sm text-stone-500 dark:text-stone-400">
            {SOURCES.map((s) => (
              <li key={s.url}>
                <a href={s.url} rel="noopener" target="_blank" className="underline decoration-stone-300 underline-offset-2 hover:text-stone-700 dark:hover:text-stone-200">
                  {s.label}
                </a>
              </li>
            ))}
          </ul>
        </section>
      )}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }} />
    </main>
  )
}
`;
}
